function varargout = processorGUI(varargin)
    % GUI Initiation Function - DO NOT EDIT
    gui_Singleton = 1;
    gui_State = struct('gui_Name',       mfilename, ...
     'gui_Singleton',  gui_Singleton, ...
     'gui_OpeningFcn', @processorGUI_OpeningFcn, ...
     'gui_OutputFcn',  @processorGUI_OutputFcn, ...
     'gui_LayoutFcn',  @processorGUI_LayoutFcn, ...
     'gui_Callback',   []);
    if nargin && ischar(varargin{1})
        gui_State.gui_Callback = str2func(varargin{1});
    end

    if nargout
        [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
    else
        gui_mainfcn(gui_State, varargin{:});
    end
end

function processorGUI_OpeningFcn(hObject, eventdata, handles, varargin) %#ok<*INUSL>
    %Software initialization function - first function run
    % This function has no output args, see OutputFcn.
    % hObject    handle to figure (see GUIDATA)
    % varargin   command line arguments to processorGUI (see VARARGIN)
    % Choose default command line output for processorGUI
    handles.output = hObject;
    % Update handles structure
    guidata(hObject, handles);
    global processorObj;
    processorObj = processor();
end


function varargout = processorGUI_OutputFcn(hObject, eventdata, handles) 
    % --- Outputs from this function are returned to the command line.
    % varargout  cell array for returning output args (see VARARGOUT);
    % hObject    handle to figure
    % eventdata  reserved - to be defined in a future version of MATLAB
    % handles    structure with handles and user data (see GUIDATA)
    % Get default command line output from handles structure
    varargout{1} = handles.output;
end

function location_Callback(hObject, eventdata, handles)
    global processorObj;
    input = get(hObject, 'String');
    processorObj.setSaveLocation(input);
end

% --- Executes during object creation, after setting all properties.
function location_CreateFcn(hObject, eventdata, handles)
    if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
        set(hObject,'BackgroundColor','white');
    end
end

function title_Callback(hObject, eventdata, handles)
    global processorObj;
    input = get(hObject, 'String');
    processorObj.setTitle(input);
end

% --- Executes during object creation, after setting all properties.
function title_CreateFcn(hObject, eventdata, handles)
    if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
        set(hObject,'BackgroundColor','white');
    end
end

% --- Executes on selection change in number.
function number_Callback(hObject, eventdata, handles)
    global processorObj;
    content = cellstr(get(hObject, 'String'));
    input = str2double(content{get(hObject, 'Value')});
    processorObj.setPicNumber(input);
end

% --- Executes during object creation, after setting all properties.
function number_CreateFcn(hObject, eventdata, handles)
    if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
        set(hObject,'BackgroundColor','white');
    end
end

% --- Executes on button press in flatFieldSeries.
function flatFieldSeries_Callback(hObject, eventdata, handles)
    global processorObj;
    processorObj.flatFieldSeries();
end
    
% --- Executes on button press in binSeries.
function binSeries_Callback(hObject, eventdata, handles)
    global processorObj;
    processorObj.binSeries();
end

% --- Executes on button press in darkSeries.
function darkSeries_Callback(hObject, eventdata, handles)
    global processorObj;
    processorObj.darkSeries();
end

% --- Executes on button press in darkSeries.
function colorCorrect_Callback(hObject, eventdata, handles)
    global processorObj;
    processorObj.colorCorrect();
end

% --- Executes on button press in displaySettings.
function displaySettings_Callback(hObject, eventdata, handles)
    global processorObj;
    processorObj.displaySettings();
end

function X_Callback(hObject, eventdata, handles)
    global processorObj;
    input = get(hObject, 'String');
    x = str2double(input);
    processorObj.setX(x);
end

% --- Executes during object creation, after setting all properties.
function X_CreateFcn(hObject, eventdata, handles) %#ok<*DEFNU,*INUSD>
    if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
        set(hObject,'BackgroundColor','white');
    end
end

function Y_Callback(hObject, eventdata, handles)
    global processorObj;
    input = get(hObject, 'String');
    y = str2double(input);
    processorObj.setY(y);
end

% --- Executes during object creation, after setting all properties.
function Y_CreateFcn(hObject, eventdata, handles)
    if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
        set(hObject,'BackgroundColor','white');
    end
end

% --- Executes on button press in graph.
function graph_Callback(hObject, eventdata, handles)
    global processorObj;
    processorObj.graph();
end

% --- Executes on button press in save.
function save_Callback(hObject, eventdata, handles)
    global processorObj;
    set(handles.graphAxes, 'Units', 'pixels');
    graphCoordinates = get(handles.graphAxes, 'Position');
    margin = [-25, -25, 50, 50];
    f = getframe(handles.figure1, graphCoordinates + margin);
    imwrite(f.cdata, [processorObj.getSaveLocation(), processorObj.getTitle(), '-graph-X', ...
        int2str(processorObj.getX()), 'Y', int2str(processorObj.getY()), 'XR', ...
        int2str(processorObj.getXRadius()), 'YR', int2str(processorObj.getYRadius()), '.tif']);
    set(handles.graphAxes, 'Units', 'characters');
    msgbox('Graph Saved')
end

% --- Executes on button press in percentGraph.
function imageDisplay_Callback(hObject, eventdata, handles)
    global processorObj;
    processorObj.imageDisplay();
end

% --- Executes on button press in percentGraph.
function percentGraph_Callback(hObject, eventdata, handles)
    global processorObj;
    input = get(hObject, 'Value');
    processorObj.setPercentGraph(input);    
end

% --- Executes on button press in flatfieldAvgGraph.
function flatfieldAvgGraph_Callback(hObject, eventdata, handles)
    global processorObj;
    input = get(hObject, 'Value');
    processorObj.setFlatfieldAvgGraph(input);    
end

% --- Executes on button press in flatfieldAvgGraph.
function flatfieldGainGraph_Callback(hObject, eventdata, handles)
    global processorObj;
    input = get(hObject, 'Value');
    processorObj.setFlatfieldGainGraph(input);    
end

% --- Executes on button press in originalGraph.
function originalGraph_Callback(hObject, eventdata, handles)
    global processorObj;
    input = get(hObject, 'Value');
    processorObj.setOriginalGraph(input);    
end

function YRadius_Callback(hObject, eventdata, handles)
    global processorObj;
    input = get(hObject, 'String');
    y = str2double(input);
    processorObj.setYRadius(y);
end

% --- Executes during object creation, after setting all properties.
function YRadius_CreateFcn(hObject, eventdata, handles)
    if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
        set(hObject,'BackgroundColor','white');
    end
end

function XRadius_Callback(hObject, eventdata, handles)
    global processorObj;
    input = get(hObject, 'String');
    r = str2double(input);
    processorObj.setXRadius(r);
end

% --- Executes during object creation, after setting all properties.
function XRadius_CreateFcn(hObject, eventdata, handles)
    if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
        set(hObject,'BackgroundColor','white');
    end
end

function correction_Callback(hObject, eventdata, handles)
    global processorObj;
    input = str2double(get(hObject, 'String'));
    processorObj.setAvgNumber(input);
end

% --- Executes during object creation, after setting all properties.
function correction_CreateFcn(hObject, eventdata, handles)
    if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
        set(hObject,'BackgroundColor','white');
    end
end

function binNum_Callback(hObject, eventdata, handles)
    global processorObj;
    input = str2double(get(hObject, 'String'));
    processorObj.setBinNumber(input);
end

% --- Executes during object creation, after setting all properties.
function binNum_CreateFcn(hObject, eventdata, handles)
    if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
        set(hObject,'BackgroundColor','white');
    end
end

function Gain_Callback(hObject, eventdata, handles)
    global processorObj;
    input = str2double(get(hObject, 'String'));
    processorObj.setGain(input);
end

function Band_Callback(hObject, eventdata, handles)
    global processorObj;
    input = str2double(get(hObject, 'String'));
    processorObj.setBand(input);
end

% --- Executes during object creation, after setting all properties.
function Gain_CreateFcn(hObject, eventdata, handles)
    if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
        set(hObject,'BackgroundColor','white');
    end
end

% --- Executes on button press in avgSeries.
function avgSeries_Callback(hObject, eventdata, handles)
    global processorObj;
    processorObj.avgProduction();
end

% --- Executes on button press in avgSeries.
function convertCube_Callback(hObject, eventdata, handles)
    global processorObj;
    processorObj.convertCube();
end

% --- Executes on button press in avgSeries.
function convertENVI_Callback(hObject, eventdata, handles)
    global processorObj;
    processorObj.convertENVI();
end

% --- Creates the GUI figure and creates then returns a handle to it. 
function h1 = processorGUI_LayoutFcn(policy)
    % policy - create a new figure or use a singleton. 'new' or 'reuse'.

    persistent hsingleton;
    if strcmpi(policy, 'reuse') & ishandle(hsingleton) %#ok<AND2>
        h1 = hsingleton;
        return;
    end

    appdata = [];
    appdata.GUIDEOptions = struct(...
        'active_h', [], ...
        'taginfo', struct(...
        'figure', 2, ...
        'uipanel', 9, ...
        'text', 26, ...
        'edit', 13, ...
        'pushbutton', 20, ...
        'togglebutton', 3, ...
        'popupmenu', 2, ...
        'radiobutton', 3, ...
        'axes', 3, ...
        'checkbox', 5), ...
        'override', 0, ...
        'release', 13, ...
        'resize', 'none', ...
        'accessibility', 'callback', ...
        'mfile', 1, ...
        'callbacks', 1, ...
        'singleton', 1, ...
        'syscolorfig', 1, ...
        'blocking', 0, ...
        'lastSavedFile', 'C:\Users\londep\Documents\MATLAB\processorGUI.m', ...
        'lastFilename', 'C:\Users\londep\Desktop\PMet\processorGUI.fig');
    appdata.lastValidTag = 'figure1';
    appdata.GUIDELayoutEditor = [];
    appdata.initTags = struct(...
        'handle', [], ...
        'tag', 'figure1');

    h1 = figure(...
    'Units','characters',...
    'Position',[98.8 25.8461538461539 140.2 35.6153846153846],...
    'Visible','on',...
    'Color',get(0,'defaultfigureColor'),...
    'IntegerHandle','off',...
    'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
    'MenuBar','none',...
    'Name','processorGUI',...
    'NumberTitle','off',...
    'Resize','off',...
    'PaperPosition',get(0,'defaultfigurePaperPosition'),...
    'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
    'ScreenPixelsPerInchMode','manual',...
    'HandleVisibility','callback',...
    'Tag','figure1',...
    'UserData',[],...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'graphAxes';

    h2 = axes(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultaxesFontUnits'),...
    'Units','characters',...
    'CameraPosition',[0.5 0.5 9.16025403784439],...
    'CameraPositionMode',get(0,'defaultaxesCameraPositionMode'),...
    'CameraTarget',[0.5 0.5 0.5],...
    'CameraTargetMode',get(0,'defaultaxesCameraTargetMode'),...
    'CameraViewAngle',6.60861036031192,...
    'CameraViewAngleMode',get(0,'defaultaxesCameraViewAngleMode'),...
    'Position',[6.6 9 59.8 15],...
    'ActivePositionProperty','position',...
    'ActivePositionPropertyMode',get(0,'defaultaxesActivePositionPropertyMode'),...
    'LooseInset',[16.562 4.38307692307692 12.103 2.98846153846154],...
    'PlotBoxAspectRatio',[1 0.652173913043478 0.652173913043478],...
    'PlotBoxAspectRatioMode',get(0,'defaultaxesPlotBoxAspectRatioMode'),...
    'XTick',[0 0.2 0.4 0.6 0.8 1],...
    'XTickMode',get(0,'defaultaxesXTickMode'),...
    'XTickLabel',{  '0'; '0.2'; '0.4'; '0.6'; '0.8'; '1' },...
    'XTickLabelMode',get(0,'defaultaxesXTickLabelMode'),...
    'YTick',[0 0.2 0.4 0.6 0.8 1],...
    'YTickMode',get(0,'defaultaxesYTickMode'),...
    'YTickLabel',{  '0'; '0.2'; '0.4'; '0.6'; '0.8'; '1' },...
    'YTickLabelMode',get(0,'defaultaxesYTickLabelMode'),...
    'Color',get(0,'defaultaxesColor'),...
    'SortMethod','childorder',...
    'SortMethodMode',get(0,'defaultaxesSortMethodMode'),...
    'CameraMode',get(0,'defaultaxesCameraMode'),...
    'DataSpaceMode',get(0,'defaultaxesDataSpaceMode'),...
    'ColorSpaceMode',get(0,'defaultaxesColorSpaceMode'),...
    'DecorationContainerMode',get(0,'defaultaxesDecorationContainerMode'),...
    'ChildContainerMode',get(0,'defaultaxesChildContainerMode'),...
    'XAxisMode',get(0,'defaultaxesXAxisMode'),...
    'XBaselineMode',get(0,'defaultaxesXBaselineMode'),...
    'YAxisMode',get(0,'defaultaxesYAxisMode'),...
    'YBaselineMode',get(0,'defaultaxesYBaselineMode'),...
    'ZAxisMode',get(0,'defaultaxesZAxisMode'),...
    'ZBaselineMode',get(0,'defaultaxesZBaselineMode'),...
    'AmbientLightSourceMode',get(0,'defaultaxesAmbientLightSourceMode'),...
    'Tag','graphAxes',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    h3 = get(h2,'title');

    set(h3,...
    'Parent',h2,...
    'Units','data',...
    'FontUnits','points',...
    'DecorationContainer',[],...
    'DecorationContainerMode','auto',...
    'Color',[0 0 0],...
    'ColorMode','auto',...
    'Position',[0.500000553386267 1.01282051282051 0.5],...
    'PositionMode','auto',...
    'String',blanks(0),...
    'Interpreter','tex',...
    'Rotation',0,...
    'RotationMode','auto',...
    'FontName','Helvetica',...
    'FontSize',10,...
    'FontAngle','normal',...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'HorizontalAlignmentMode','auto',...
    'VerticalAlignment','bottom',...
    'VerticalAlignmentMode','auto',...
    'EdgeColor','none',...
    'LineStyle','-',...
    'LineWidth',0.5,...
    'BackgroundColor','none',...
    'Margin',2,...
    'Clipping','off',...
    'Layer','middle',...
    'LayerMode','auto',...
    'FontSmoothing','on',...
    'FontSmoothingMode','auto',...
    'DisplayName',blanks(0),...
    'IncludeRenderer','on',...
    'IsContainer','off',...
    'IsContainerMode','auto',...
    'HelpTopicKey',blanks(0),...
    'BusyAction','queue',...
    'Interruptible','on',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
    'DeleteFcn',blanks(0),...
    'ButtonDownFcn',blanks(0),...
    'Tag',blanks(0),...
    'SelectionHighlightMode','manual',...
    'HitTest','on',...
    'PickableParts','visible',...
    'PickablePartsMode','auto',...
    'XLimInclude','on',...
    'YLimInclude','on',...
    'ZLimInclude','on',...
    'CLimInclude','on',...
    'ALimInclude','on',...
    'Description','Axes Title',...
    'DescriptionMode','auto',...
    'Visible','on',...
    'Serializable','on',...
    'HandleVisibility','off',...
    'TransformForPrintFcnImplicitInvoke','on',...
    'TransformForPrintFcnImplicitInvokeMode','auto');

    h4 = get(h2,'xlabel');

    set(h4,...
    'Parent',h2,...
    'Units','data',...
    'FontUnits','points',...
    'DecorationContainer',[],...
    'DecorationContainerMode','auto',...
    'Color',[0 0 0],...
    'ColorMode','auto',...
    'Position',[0.500000476837158 -0.12136751876937 1.77635683940025e-15],...
    'PositionMode','auto',...
    'String',blanks(0),...
    'Interpreter','tex',...
    'Rotation',0,...
    'RotationMode','auto',...
    'FontName','Helvetica',...
    'FontSize',10,...
    'FontAngle','normal',...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'HorizontalAlignmentMode','auto',...
    'VerticalAlignment','top',...
    'VerticalAlignmentMode','auto',...
    'EdgeColor','none',...
    'LineStyle','-',...
    'LineWidth',0.5,...
    'BackgroundColor','none',...
    'Margin',2,...
    'Clipping','off',...
    'Layer','back',...
    'LayerMode','auto',...
    'FontSmoothing','on',...
    'FontSmoothingMode','auto',...
    'DisplayName',blanks(0),...
    'IncludeRenderer','on',...
    'IsContainer','off',...
    'IsContainerMode','auto',...
    'HelpTopicKey',blanks(0),...
    'BusyAction','queue',...
    'Interruptible','on',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
    'DeleteFcn',blanks(0),...
    'ButtonDownFcn',blanks(0),...
    'Tag',blanks(0),...
    'SelectionHighlightMode','manual',...
    'HitTest','on',...
    'PickableParts','visible',...
    'PickablePartsMode','auto',...
    'XLimInclude','on',...
    'YLimInclude','on',...
    'ZLimInclude','on',...
    'CLimInclude','on',...
    'ALimInclude','on',...
    'Description','AxisRulerBase Label',...
    'DescriptionMode','auto',...
    'Visible','on',...
    'Serializable','on',...
    'HandleVisibility','off',...
    'TransformForPrintFcnImplicitInvoke','on',...
    'TransformForPrintFcnImplicitInvokeMode','auto');

    h5 = get(h2,'ylabel');

    set(h5,...
    'Parent',h2,...
    'Units','data',...
    'FontUnits','points',...
    'DecorationContainer',[],...
    'DecorationContainerMode','auto',...
    'Color',[0 0 0],...
    'ColorMode','auto',...
    'Position',[-0.0947603102578235 0.500000476837158 1.77635683940025e-15],...
    'PositionMode','auto',...
    'String',blanks(0),...
    'Interpreter','tex',...
    'Rotation',90,...
    'RotationMode','auto',...
    'FontName','Helvetica',...
    'FontSize',10,...
    'FontAngle','normal',...
    'FontWeight','normal',...
    'HorizontalAlignment','center',...
    'HorizontalAlignmentMode','auto',...
    'VerticalAlignment','bottom',...
    'VerticalAlignmentMode','auto',...
    'EdgeColor','none',...
    'LineStyle','-',...
    'LineWidth',0.5,...
    'BackgroundColor','none',...
    'Margin',2,...
    'Clipping','off',...
    'Layer','back',...
    'LayerMode','auto',...
    'FontSmoothing','on',...
    'FontSmoothingMode','auto',...
    'DisplayName',blanks(0),...
    'IncludeRenderer','on',...
    'IsContainer','off',...
    'IsContainerMode','auto',...
    'HelpTopicKey',blanks(0),...
    'BusyAction','queue',...
    'Interruptible','on',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
    'DeleteFcn',blanks(0),...
    'ButtonDownFcn',blanks(0),...
    'Tag',blanks(0),...
    'SelectionHighlightMode','manual',...
    'HitTest','on',...
    'PickableParts','visible',...
    'PickablePartsMode','auto',...
    'XLimInclude','on',...
    'YLimInclude','on',...
    'ZLimInclude','on',...
    'CLimInclude','on',...
    'ALimInclude','on',...
    'Description','AxisRulerBase Label',...
    'DescriptionMode','auto',...
    'Visible','on',...
    'Serializable','on',...
    'HandleVisibility','off',...
    'TransformForPrintFcnImplicitInvoke','on',...
    'TransformForPrintFcnImplicitInvokeMode','auto');

    h6 = get(h2,'zlabel');

    set(h6,...
    'Parent',h2,...
    'Units','data',...
    'FontUnits','points',...
    'DecorationContainer',[],...
    'DecorationContainerMode','auto',...
    'Color',[0 0 0],...
    'ColorMode','auto',...
    'Position',[0 0 0],...
    'PositionMode','auto',...
    'String',blanks(0),...
    'Interpreter','tex',...
    'Rotation',0,...
    'RotationMode','auto',...
    'FontName','Helvetica',...
    'FontSize',10,...
    'FontAngle','normal',...
    'FontWeight','normal',...
    'HorizontalAlignment','right',...
    'HorizontalAlignmentMode','auto',...
    'VerticalAlignment','middle',...
    'VerticalAlignmentMode','auto',...
    'EdgeColor','none',...
    'LineStyle','-',...
    'LineWidth',0.5,...
    'BackgroundColor','none',...
    'Margin',2,...
    'Clipping','off',...
    'Layer','middle',...
    'LayerMode','auto',...
    'FontSmoothing','on',...
    'FontSmoothingMode','auto',...
    'DisplayName',blanks(0),...
    'IncludeRenderer','on',...
    'IsContainer','off',...
    'IsContainerMode','auto',...
    'HelpTopicKey',blanks(0),...
    'BusyAction','queue',...
    'Interruptible','on',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ,...
    'DeleteFcn',blanks(0),...
    'ButtonDownFcn',blanks(0),...
    'Tag',blanks(0),...
    'SelectionHighlightMode','manual',...
    'HitTest','on',...
    'PickableParts','visible',...
    'PickablePartsMode','auto',...
    'XLimInclude','on',...
    'YLimInclude','on',...
    'ZLimInclude','on',...
    'CLimInclude','on',...
    'ALimInclude','on',...
    'Description','AxisRulerBase Label',...
    'DescriptionMode','auto',...
    'Visible','off',...
    'Serializable','on',...
    'HandleVisibility','off',...
    'TransformForPrintFcnImplicitInvoke','on',...
    'TransformForPrintFcnImplicitInvokeMode','auto');

    appdata = [];
    appdata.lastValidTag = 'uipanel3';

    h7 = uipanel(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuipanelFontUnits'),...
    'Units',get(0,'defaultuipanelUnits'),...
    'Title','Series Processing',...
    'Position',[0.513056835637481 0.0263930885529158 0.439324116743472 0.401490280777538],...
    'Clipping','off',...
    'Tag','uipanel3',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'number';

    h8 = uicontrol(...
    'Parent',h7,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','33',...
    'Style','edit',...
    'Value',1,...
    'Position',[7.6 7.28162393162393 12.2 2],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)processorGUI('number_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)processorGUI('number_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
    'Tag','number');

    appdata = [];
    appdata.lastValidTag = 'text13';

    h9 = uicontrol(...
    'Parent',h7,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Image Number:',...
    'Style','text',...
    'Position',[4.8 9.20470085470085 18.8 1.42307692307692],...
    'Children',[],...
    'Tag','text13',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'flatFieldSeries';

    h10 = uicontrol(...
    'Parent',h7,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Flat-Field Series',...
    'Position',[29.8 3.005854700854701 23 2.03846153846154],...
    'Callback',@(hObject,eventdata)processorGUI('flatFieldSeries_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Tag','flatFieldSeries',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'colorCorrect';

    h11 = uicontrol(...
    'Parent',h7,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Color Correction',...
    'Position',[30.2 0.5 22.6 2.26153846153846],...
    'Callback',@(hObject,eventdata)processorGUI('colorCorrect_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Tag','colorCorrect',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ); %#ok<*NASGU>

    appdata = [];
    appdata.lastValidTag = 'text25';

    h12 = uicontrol(...
    'Parent',h7,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Averaging Factor:',...
    'Style','text',...
    'Position',[4.2 6.12777777777778 18.2 1.07692307692308],...
    'Children',[],...
    'ParentMode','manual',...
    'Tag','text25',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'correction';

    h13 = uicontrol(...
    'Parent',h7,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','2',...
    'Style','edit',...
    'Position',[7.8 4.20470085470085 12 1.84615384615385],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)processorGUI('correction_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'ParentMode','manual',...
    'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)processorGUI('correction_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
    'Tag','correction');

    appdata = [];
    appdata.lastValidTag = 'avgSeries';

    h14 = uicontrol(...
    'Parent',h7,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Average Series',...
    'Style',get(0,'defaultuicontrolStyle'),...
    'Position',[30 10.20769230769231 22.8 2.07692307692308],...
    'Callback',@(hObject,eventdata)processorGUI('avgSeries_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'ParentMode','manual',...
    'Tag','avgSeries',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'avgSeries';

    h14 = uicontrol(...
    'Parent',h7,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Average Series',...
    'Style',get(0,'defaultuicontrolStyle'),...
    'Position',[30 10.20769230769231 22.8 2.07692307692308],...
    'Callback',@(hObject,eventdata)processorGUI('avgSeries_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'ParentMode','manual',...
    'Tag','avgSeries',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'convertENVI';

    h43 = uicontrol(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Convert to ENVI',...
    'Style',get(0,'defaultuicontrolStyle'),...
    'Position',[10 2.20769230769231 22.8 1.77692307692308],...
    'Callback',@(hObject,eventdata)processorGUI('convertENVI_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'ParentMode','manual',...
    'Tag','convertENVI',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'binSeries';

    h37 = uicontrol(...
    'Parent',h7,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Bin Series',...
    'Style',get(0,'defaultuicontrolStyle'),...
    'Position',[30 7.90769230769231 22.8 2.07692307692308],...
    'Callback',@(hObject,eventdata)processorGUI('binSeries_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'ParentMode','manual',...
    'Tag','binSeries',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'darkSeries';

    h37 = uicontrol(...
    'Parent',h7,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Dark Subtract Series',...
    'Style',get(0,'defaultuicontrolStyle'),...
    'Position',[30 5.50769230769231 22.8 2.07692307692308],...
    'Callback',@(hObject,eventdata)processorGUI('darkSeries_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'ParentMode','manual',...
    'Tag','darkSeries',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );


    appdata = [];
    appdata.lastValidTag = 'uipanel7';

    h15 = uipanel(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuipanelFontUnits'),...
    'Units','characters',...
    'Title','File Upload',...
    'Position',[9.8 27.8461538461538 48 6.07692307692308],...
    'Clipping','off',...
    'Tag','uipanel7',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'location';

    h16 = uicontrol(...
    'Parent',h15,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','normalized',...
    'String','C:/',...
    'Style','edit',...
    'Position',[0.0932203389830508 0.575757575757576 0.860169491525424 0.348484848484849],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)processorGUI('location_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)processorGUI('location_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
    'Tag','location');

    appdata = [];
    appdata.lastValidTag = 'text12';

    h17 = uicontrol(...
    'Parent',h15,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Seriesf Title:',...
    'Style','text',...
    'Position',[2 0.846153846153834 14.4 1.23076923076923],...
    'Children',[],...
    'Tag','text12',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} ); %#ok<*NASGU>

    appdata = [];
    appdata.lastValidTag = 'title';

    h18 = uicontrol(...
    'Parent',h15,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','test',...
    'Style','edit',...
    'Position',[16.2 0.69230769230768 20.2 1.69230769230769],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)processorGUI('title_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)processorGUI('title_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
    'Tag','title');

    appdata = [];
    appdata.lastValidTag = 'uipanel6';

    h19 = uipanel(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuipanelFontUnits'),...
    'Units','characters',...
    'Title','Advanced Commands',...
    'Position',[72.6 22.5384615384615 56.2 11.23076923076923],...
    'Clipping','off',...
    'Tag','uipanel6',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'displaySettings';

    h20 = uicontrol(...
    'Parent',h19,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Display Settings',...
    'Position',[3 7.38461538461539 18.6 1.69230769230769],...
    'Callback',@(hObject,eventdata)processorGUI('displaySettings_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Tag','displaySettings',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'percentGraph';

    h21 = uicontrol(...
    'Parent',h19,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Percent Graph',...
    'Style','checkbox',...
    'Position',[4.8 3.30769230769231 18.2 1.76923076923077],...
    'Callback',@(hObject,eventdata)processorGUI('percentGraph_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Tag','percentGraph',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'flatfieldAvgGraph';

    h23 = uicontrol(...
    'Parent',h19,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Flat-Field Average Graph',...
    'Style','checkbox',...
    'Position',[4.8 1.23076923076923 30.2 1.76923076923077],...
    'Callback',@(hObject,eventdata)processorGUI('flatfieldAvgGraph_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Tag','flatfieldAvgGraph',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'flatfieldAvgGraph';

    h39 = uicontrol(...
    'Parent',h19,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Flat-Field Gain Graph',...
    'Style','checkbox',...
    'Position',[24.8 3.33076923076923 30.2 1.76923076923077],...
    'Callback',@(hObject,eventdata)processorGUI('flatfieldGainGraph_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Tag','flatfieldGainGraph',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'originalGraph';

    h24 = uicontrol(...
    'Parent',h19,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Original Series Graph',...
    'Style','checkbox',...
    'Position',[4.8 5.23076923076923 26.6 1.76923076923077],...
    'Callback',@(hObject,eventdata)processorGUI('originalGraph_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Tag','originalGraph',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'uipanel8';

    h25 = uipanel(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuipanelFontUnits'),...
    'Units','characters',...
    'Title','Graph Settings',...
    'Position',[73 16.3076923076923 60.4 6],...
    'Clipping','off',...
    'Tag','uipanel8',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'X';

    h26 = uicontrol(...
    'Parent',h25,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','1',...
    'Style','edit',...
    'Position',[12.6 2.92307692307692 7.6 1.69230769230769],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)processorGUI('X_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)processorGUI('X_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
    'Tag','X');

    appdata = [];
    appdata.lastValidTag = 'Y';

    h27 = uicontrol(...
    'Parent',h25,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','1',...
    'Style','edit',...
    'Position',[12.6 0.769230769230769 7.6 1.69230769230769],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)processorGUI('Y_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)processorGUI('Y_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
    'Tag','Y');

    appdata = [];
    appdata.lastValidTag = 'text14';

    h28 = uicontrol(...
    'Parent',h25,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Center X:',...
    'Style','text',...
    'Position',[1.4 3 10 1.30769230769231],...
    'Children',[],...
    'Tag','text14',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'text15';

    h29 = uicontrol(...
    'Parent',h25,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Center Y:',...
    'Style','text',...
    'Position',[1.5 0.846153846153846 10 1.30769230769231],...
    'Children',[],...
    'Tag','text15',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'graph';

    h30 = uicontrol(...
    'Parent',h25,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Graph',...
    'Position',[39.4 2.69230769230769 18 1.92307692307692],...
    'Callback',@(hObject,eventdata)processorGUI('graph_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Tag','graph',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'save';

    h31 = uicontrol(...
    'Parent',h25,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Save',...
    'Position',[39.2 0.769230769230769 18.2 1.76923076923077],...
    'Callback',@(hObject,eventdata)processorGUI('save_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Tag','save',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'imageDisplay';

    h41 = uicontrol(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Display',...
    'Position',[39.2 0.769230769230769 18.2 1.76923076923077],...
    'Callback',@(hObject,eventdata)processorGUI('imageDisplay_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'Tag','imageDisplay',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'text16';

    h32 = uicontrol(...
    'Parent',h25,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','X Radius:',...
    'Style','text',...
    'Position',[20.2 3.10769230769231 10.8 1.30769230769231],...
    'Children',[],...
    'Tag','text16',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'text17';

    h33 = uicontrol(...
    'Parent',h25,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Y Radius:',...
    'Style','text',...
    'Position',[20.2 0.869230769230769 10.8 1.30769230769231],...
    'Children',[],...
    'Tag','text17',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'YRadius';

    h34 = uicontrol(...
    'Parent',h25,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','1',...
    'Style','edit',...
    'Position',[30.8 0.769230769230769 7.6 1.69230769230769],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)processorGUI('YRadius_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)processorGUI('YRadius_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
    'Tag','YRadius');

    appdata = [];
    appdata.lastValidTag = 'XRadius';

    h35 = uicontrol(...
    'Parent',h25,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','1',...
    'Style','edit',...
    'Position',[30.8 2.92307692307692 7.6 1.69230769230769],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)processorGUI('XRadius_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)processorGUI('XRadius_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
    'Tag','XRadius');

    h36 = uicontrol(...
    'Parent',h19,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Gain:',...
    'Style','text',...
    'Position',[23 7.5 6 1.30769230769231],...
    'Children',[],...
    'Tag','gainText',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    h40 = uicontrol(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Band:',...
    'Style','text',...
    'Position',[23 4.5 6 1.30769230769231],...
    'Children',[],...
    'Tag','gainText',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'gain';

    h35 = uicontrol(...
    'Parent',h19,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','1',...
    'Style','edit',...
    'Position',[29.8 7.5 7.6 1.69230769230769],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)processorGUI('Gain_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)processorGUI('Gain_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
    'Tag','gain');

    appdata = [];
    appdata.lastValidTag = 'band';

    h35 = uicontrol(...
    'Parent',h1,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','550',...
    'Style','edit',...
    'Position',[29.8 4.5 7.6 1.69230769230769],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)processorGUI('Band_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)processorGUI('Band_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
    'Tag','gain');

    appdata = [];
    appdata.lastValidTag = 'textBin';

    h36 = uicontrol(...
    'Parent',h7,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','Binning Factor:',...
    'Style','text',...
    'Position',[4.2 2.72777777777778 18.2 1.07692307692308],...
    'Children',[],...
    'ParentMode','manual',...
    'Tag','textBin',...
    'CreateFcn', {@local_CreateFcn, blanks(0), appdata} );

    appdata = [];
    appdata.lastValidTag = 'binNum';

    h36 = uicontrol(...
    'Parent',h7,...
    'FontUnits',get(0,'defaultuicontrolFontUnits'),...
    'Units','characters',...
    'String','1',...
    'Style','edit',...
    'Position',[7.8 0.60470085470085 12 1.84615384615385],...
    'BackgroundColor',[1 1 1],...
    'Callback',@(hObject,eventdata)processorGUI('binNum_Callback',hObject,eventdata,guidata(hObject)),...
    'Children',[],...
    'ParentMode','manual',...
    'CreateFcn', {@local_CreateFcn, @(hObject,eventdata)processorGUI('binNum_CreateFcn',hObject,eventdata,guidata(hObject)), appdata} ,...
    'Tag','binNum');

    hsingleton = h1;
end

% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)
    if ~isempty(appdata)
       names = fieldnames(appdata);
       for i=1:length(names)
           name = char(names(i));
           setappdata(hObject, name, getfield(appdata,name)); %#ok<GFLD>
       end
    end

    if ~isempty(createfcn)
       if isa(createfcn,'function_handle')
           createfcn(hObject, eventdata);
       else
           eval(createfcn);
       end
    end
end

% --- Handles default GUIDE GUI creation and callback dispatch
function varargout = gui_mainfcn(gui_State, varargin)

    gui_StateFields =  {'gui_Name'
        'gui_Singleton'
        'gui_OpeningFcn'
        'gui_OutputFcn'
        'gui_LayoutFcn'
        'gui_Callback'};
    gui_Mfile = '';
    for i=1:length(gui_StateFields)
        if ~isfield(gui_State, gui_StateFields{i})
            error(message('MATLAB:guide:StateFieldNotFound', gui_StateFields{ i }, gui_Mfile));
        elseif isequal(gui_StateFields{i}, 'gui_Name')
            gui_Mfile = [gui_State.(gui_StateFields{i}), '.m'];
        end
    end

    numargin = length(varargin);

    if numargin == 0
        % processorGUI
        % create the GUI only if we are not in the process of loading it
        % already
        gui_Create = true;
    elseif local_isInvokeActiveXCallback(gui_State, varargin{:})
        % processorGUI(ACTIVEX,...)
        vin{1} = gui_State.gui_Name;
        vin{2} = [get(varargin{1}.Peer, 'Tag'), '_', varargin{end}];
        vin{3} = varargin{1};
        vin{4} = varargin{end-1};
        vin{5} = guidata(varargin{1}.Peer);
        feval(vin{:});
        return;
    elseif local_isInvokeHGCallback(gui_State, varargin{:})
        % processorGUI('CALLBACK',hObject,eventData,handles,...)
        gui_Create = false;
    else
        % processorGUI(...)
        % create the GUI and hand varargin to the openingfcn
        gui_Create = true;
    end

    if ~gui_Create
        % In design time, we need to mark all components possibly created in
        % the coming callback evaluation as non-serializable. This way, they
        % will not be brought into GUIDE and not be saved in the figure file
        % when running/saving the GUI from GUIDE.
        designEval = false;
        if (numargin>1 && ishghandle(varargin{2}))
            fig = varargin{2};
            while ~isempty(fig) && ~ishghandle(fig,'figure')
                fig = get(fig,'parent');
            end
            
            designEval = isappdata(0,'CreatingGUIDEFigure') || (isscalar(fig)&&isprop(fig,'GUIDEFigure'));
        end
            
        if designEval
            beforeChildren = findall(fig);
        end
        
        % evaluate the callback now
        varargin{1} = gui_State.gui_Callback;
        if nargout
            [varargout{1:nargout}] = feval(varargin{:});
        else       
            feval(varargin{:});
        end
        
        % Set serializable of objects created in the above callback to off in
        % design time. Need to check whether figure handle is still valid in
        % case the figure is deleted during the callback dispatching.
        if designEval && ishghandle(fig)
            set(setdiff(findall(fig),beforeChildren), 'Serializable','off');
        end
    else
        if gui_State.gui_Singleton
            gui_SingletonOpt = 'reuse';
        else
            gui_SingletonOpt = 'new';
        end

        % Check user passing 'visible' P/V pair first so that its value can be
        % used by oepnfig to prevent flickering
        gui_Visible = 'auto';
        gui_VisibleInput = '';
        for index=1:2:length(varargin)
            if length(varargin) == index || ~ischar(varargin{index})
                break;
            end

            % Recognize 'visible' P/V pair
            len1 = min(length('visible'),length(varargin{index}));
            len2 = min(length('off'),length(varargin{index+1}));
            if ischar(varargin{index+1}) && strncmpi(varargin{index},'visible',len1) && len2 > 1
                if strncmpi(varargin{index+1},'off',len2)
                    gui_Visible = 'invisible';
                    gui_VisibleInput = 'off';
                elseif strncmpi(varargin{index+1},'on',len2)
                    gui_Visible = 'visible';
                    gui_VisibleInput = 'on';
                end
            end
        end
        
        % Open fig file with stored settings.  Note: This executes all component
        % specific CreateFunctions with an empty HANDLES structure.

        
        % Do feval on layout code in m-file if it exists
        gui_Exported = ~isempty(gui_State.gui_LayoutFcn);
        % this application data is used to indicate the running mode of a GUIDE
        % GUI to distinguish it from the design mode of the GUI in GUIDE. it is
        % only used by actxproxy at this time.   
        setappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name]),1); %#ok<DEPGENAM>
        if gui_Exported
            gui_hFigure = feval(gui_State.gui_LayoutFcn, gui_SingletonOpt);

            % make figure invisible here so that the visibility of figure is
            % consistent in OpeningFcn in the exported GUI case
            if isempty(gui_VisibleInput)
                gui_VisibleInput = get(gui_hFigure,'Visible');
            end
            set(gui_hFigure,'Visible','off')

            % openfig (called by local_openfig below) does this for guis without
            % the LayoutFcn. Be sure to do it here so guis show up on screen.
            movegui(gui_hFigure,'onscreen');
        else
            gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
            % If the figure has InGUIInitialization it was not completely created
            % on the last pass.  Delete this handle and try again.
            if isappdata(gui_hFigure, 'InGUIInitialization')
                delete(gui_hFigure);
                gui_hFigure = local_openfig(gui_State.gui_Name, gui_SingletonOpt, gui_Visible);
            end
        end
        if isappdata(0, genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name])) %#ok<DEPGENAM>
            rmappdata(0,genvarname(['OpenGuiWhenRunning_', gui_State.gui_Name])); %#ok<DEPGENAM>
        end

        % Set flag to indicate starting GUI initialization
        setappdata(gui_hFigure,'InGUIInitialization',1);

        % Fetch GUIDE Application options
        gui_Options = getappdata(gui_hFigure,'GUIDEOptions');
        % Singleton setting in the GUI M-file takes priority if different
        gui_Options.singleton = gui_State.gui_Singleton;

        if ~isappdata(gui_hFigure,'GUIOnScreen')
            % Adjust background color
            if gui_Options.syscolorfig
                set(gui_hFigure,'Color', get(0,'DefaultUicontrolBackgroundColor'));
            end

            % Generate HANDLES structure and store with GUIDATA. If there is
            % user set GUI data already, keep that also.
            data = guidata(gui_hFigure);
            handles = guihandles(gui_hFigure);
            if ~isempty(handles)
                if isempty(data)
                    data = handles;
                else
                    names = fieldnames(handles);
                    for k=1:length(names)
                        data.(char(names(k)))=handles.(char(names(k)));
                    end
                end
            end
            guidata(gui_hFigure, data);
        end

        % Apply input P/V pairs other than 'visible'
        for index=1:2:length(varargin)
            if length(varargin) == index || ~ischar(varargin{index})
                break;
            end

            len1 = min(length('visible'),length(varargin{index}));
            if ~strncmpi(varargin{index},'visible',len1)
                try set(gui_hFigure, varargin{index}, varargin{index+1}), catch break, end %#ok<SEPEX>
            end
        end

        % If handle visibility is set to 'callback', turn it on until finished
        % with OpeningFcn
        gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
        if strcmp(gui_HandleVisibility, 'callback')
            set(gui_hFigure,'HandleVisibility', 'on');
        end

        feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

        if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
            % Handle the default callbacks of predefined toolbar tools in this
            % GUI, if any
            guidemfile('restoreToolbarToolPredefinedCallback',gui_hFigure); 
            
            % Update handle visibility
            set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);

            % Call openfig again to pick up the saved visibility or apply the
            % one passed in from the P/V pairs
            if ~gui_Exported
                gui_hFigure = local_openfig(gui_State.gui_Name, 'reuse',gui_Visible);
            elseif ~isempty(gui_VisibleInput)
                set(gui_hFigure,'Visible',gui_VisibleInput);
            end
            if strcmpi(get(gui_hFigure, 'Visible'), 'on')
                figure(gui_hFigure);
                
                if gui_Options.singleton
                    setappdata(gui_hFigure,'GUIOnScreen', 1);
                end
            end

            % Done with GUI initialization
            if isappdata(gui_hFigure,'InGUIInitialization')
                rmappdata(gui_hFigure,'InGUIInitialization');
            end

            % If handle visibility is set to 'callback', turn it on until
            % finished with OutputFcn
            gui_HandleVisibility = get(gui_hFigure,'HandleVisibility');
            if strcmp(gui_HandleVisibility, 'callback')
                set(gui_hFigure,'HandleVisibility', 'on');
            end
            gui_Handles = guidata(gui_hFigure);
        else
            gui_Handles = [];
        end

        if nargout
            [varargout{1:nargout}] = feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
        else
            feval(gui_State.gui_OutputFcn, gui_hFigure, [], gui_Handles);
        end

        if isscalar(gui_hFigure) && ishghandle(gui_hFigure)
            set(gui_hFigure,'HandleVisibility', gui_HandleVisibility);
        end
    end
end

function gui_hFigure = local_openfig(name, singleton, visible)

    % openfig with three arguments was new from R13. Try to call that first, if
    % failed, try the old openfig.
    if nargin('openfig') == 2
        % OPENFIG did not accept 3rd input argument until R13,
        % toggle default figure visible to prevent the figure
        % from showing up too soon.
        gui_OldDefaultVisible = get(0,'defaultFigureVisible');
        set(0,'defaultFigureVisible','off');
        gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton);
        set(0,'defaultFigureVisible',gui_OldDefaultVisible);
    else
        % Call version of openfig that accepts 'auto' option"
        gui_hFigure = matlab.hg.internal.openfigLegacy(name, singleton, visible);  
    %     %workaround for CreateFcn not called to create ActiveX
    %         peers=findobj(findall(allchild(gui_hFigure)),'type','uicontrol','style','text');    
    %         for i=1:length(peers)
    %             if isappdata(peers(i),'Control')
    %                 actxproxy(peers(i));
    %             end            
    %         end
    end
end

function result = local_isInvokeActiveXCallback(gui_State, varargin)
    try
        result = ispc && iscom(varargin{1}) ...
                 && isequal(varargin{1},gcbo);
    catch
        result = false;
    end
end

function result = local_isInvokeHGCallback(gui_State, varargin)
    try
        fhandle = functions(gui_State.gui_Callback);
        result = ~isempty(findstr(gui_State.gui_Name,fhandle.file)) || ...
                 (ischar(varargin{1}) ...
                 && isequal(ishghandle(varargin{2}), 1) ...
                 && (~isempty(strfind(varargin{1},[get(varargin{2}, 'Tag'), '_'])) || ...
                    ~isempty(strfind(varargin{1}, '_CreateFcn'))) ); %#ok<FSTR>
    catch
        result = false;
    end
end